spring.application.name=club-escalade
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always